name: WarzonePlugin
author: 6u5t4v/g6u5t4v
description: a plugin meant for WarzoneMania minecraft server, made by 6u5t4v
version: 1.0
main: com.furnesse.warzone.WarzonePlugin
api-version: 1.14
commands:
  warzone:
    description: main command command for the plugin
    aliases: [w, warzoneplugin, warzonep]
    usage: /w help

      